---
- name: Start pg_recvlogical
  systemd:
    name: pg_recvlogical
    state: restarted
    enabled: yes
    daemon_reload: yes
- name: Start replication
  systemd:
    name: replication.target
    state: started
    enabled: yes
    daemon_reload: yes
