---
- name: Install postgresql-client
  package:
    name: postgresql-client
    state: present

- name: create re_dms group
  group:
    name: re_dms
    state: present

- name: create re_dms user
  user:
    name: re_dms
    groups: re_dms
    shell: /sbin/nologin
    append: yes
    state: present
    create_home: no

- name: create ext4 filesystem
  community.general.filesystem:
    fstype: ext4
    dev: "{{filesystemDev}}"

- name: mount filesystem
  ansible.posix.mount:
    path: /re_dms
    src: "{{filesystemDev}}"
    fstype: ext4
    opts: rw,auto
    state: mounted

- name: create output_wal dir
  ansible.builtin.file:
    path: /re_dms/output_wal
    state: directory
    owner: re_dms
    group: re_dms
    mode: '0750'

- name: Copy systemd config file to server
  copy:
    src: "re_dms.conf.{{ env }}"
    dest: /etc/re_dms.conf
    owner: root
    group: root
    mode: 0660
  tags: copy_config
  notify:
    - Start re_dms

- name: Copy systemd service file to server
  copy:
    src: re_dms.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start re_dms

- name: Copy binary to server
  copy:
    src: re_dms
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
  notify:
    - Start re_dms
