---
# tasks file for cloudwatch

# this entire next task is a hack to get the following
# cwa_conf_json_file_content_variable: "{{ lookup('file', 'example_cloudwatch.json') | from_json }}"
# this is needed because when you include_role below, variables are executed in the child roles
# context. if something from the included role references this variable within a `vars/something.yml`
# file it will then have an incorrect file searchpath, so lookup returns None
# which messes the included role up.
- name: read_config_file
  local_action:
    module: ansible.builtin.shell
    _raw_params: "sed -e 's/TARGET_NAME/re_dms_{{env}}/g' {{ role_path }}/files/example_cloudwatch.json"
  register: cwa_conf_json_file_content_variable
  become: false
  run_once: true

# - name: debug
#   debug:
#     msg: "{{ cwa_conf_json_file_content_variable.stdout }}"
#   tags: debug

- name: Add the user cwauser and add them to the group adm to allow them to read syslog
  user:
    name: cwagent
    comment: CloudWatchAgent
    group: adm

- name: setup re_dms log group
  local_action:
    module: community.aws.cloudwatchlogs_log_group
    log_group_name: "re_dms_{{env}}"
    retention: 365
  become: false
  tags: log-group

- name: create credentials directory
  ansible.builtin.file:
    path: /home/cwagent/.aws
    state: directory
  tags: copy-credentials

- name: copy cloudwatch credentials to server
  ansible.builtin.template:
    src: credentials_template.j2
    dest: /home/cwagent/.aws/credentials
    owner: cwagent
    mode: '0600'
  tags: copy-credentials

# this will install the cloudwatch agent, but not start anything.
- name: install and configure amazon cloudwatch agent
  include_role:
    name: christiangda.amazon_cloudwatch_agent
  vars:
    cwa_conf_json_file_content: "{{ cwa_conf_json_file_content_variable.stdout }}"
    cwa_agent_mode: "ec2"
  tags: install-agent

# note logs: tail /opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log

- name: start systemd service
  ansible.builtin.systemd:
    name: amazon-cloudwatch-agent
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Copy systemd service file to server
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /usr/local/bin
    owner: re_dms
    mode: 0755
  loop:
    - measure_number_of_wal_files.sh
    - measure_age_of_oldest_wal_file.sh
    - measure_age_of_youngest_wal_file.sh
    - dead_tuple_percentages.sh
    - dead_tuple_percentages.sql
    - replication_slot_lag.sh
    - replication_slot_lag.sql
    - vacuum_analyze.sh
  tags: statsd-metrics

- name: Git checkout vacuum analyze tool
  ansible.builtin.git:
    repo: 'https://github.com/BhuviTheDataGuy/RedShift-ToolKit'
    dest: /usr/local/bin/RedShift-ToolKit
    update: false

- name: Make vacuum analyze script executable
  ansible.builtin.file:
    path: /usr/local/bin/RedShift-ToolKit/VacuumAnalyzeUtility/vacuum-analyze-utility.sh
    owner: root
    group: re_dms
    mode: '0750'

- name: set custom cron metric reporting to statsd
  ansible.builtin.cron:
    name: 'check number of wal files.'
    minute: '*' # these are defaults but explicitly every minute
    hour: '*'
    weekday: '*'
    user: 're_dms'
    # calculate number of wal files
    # pipefail to exit early
    # echo as a guage to netcat, and send to default statsd collection agent.
    job: "(/usr/local/bin/measure_number_of_wal_files.sh ; /usr/local/bin/measure_age_of_oldest_wal_file.sh ; /usr/local/bin/measure_age_of_youngest_wal_file.sh) 2>&1 | logger -t bash_metrics"
  tags: statsd-metrics

- name: set custom dead tuple reporting to statsd
  ansible.builtin.cron:
    name: 'check number of dead tuples.'
    minute: '*/5' # every 5 minutes
    hour: '*'
    weekday: '*'
    user: 're_dms'
    job: "/usr/local/bin/dead_tuple_percentages.sh 2>&1 | logger -t dead_tuple_percentages"
  tags: statsd-metrics

- name: set custom replication slot lag reporting to statsd
  ansible.builtin.cron:
    name: 'check replication slot lag'
    minute: '*/5' # every 5 minutes
    hour: '*'
    weekday: '*'
    user: 're_dms'
    job: "/usr/local/bin/replication_slot_lag.sh 2>&1 | logger -t replication_slot_lag"
  tags: statsd-metrics

- name: vacuum analyze public tables
  ansible.builtin.cron:
    name: 'vacuum analyze public tables'
    minute: '0' # 9pm nightly
    hour: '21'
    weekday: '*'
    user: 're_dms'
    job: "/usr/local/bin/vacuum_analyze.sh 2>&1 | logger -t vacuum_analyze"
  tags: statsd-metrics
